- hosts: all
  gather_facts: no
  collections:
    - arubanetworks.aos_switch
  vars:
    ansible_connection: network_cli
  tasks:
    - include: project_update.yml
    - name: Execute show run on the switch
      arubaoss_command:
        commands: ['show run']
      register: out

    - debug: var=out.stdout_lines
